
build:
  version: "3.0"

loans:
  message: "Welcome to Bank accounts related Production APIs "
  contactDetails:
    name: "Sreenivas- Developer"
    email: "Sreenivas@gmail.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345